export default [
	{
		id: 1,
		number: '2025-0001',
		header: "Cover page",
		type: "Cover page",
		status: "Draft",
		target: "18",
		serviceDate: "2025",
		team: "Eddie Lake",
	},
	{
		id: 2,
		number: '2025-0002',
		header: "Table of contents",
		type: "Table of contents",
		status: "Confirmed",
		target: "29",
		serviceDate: "24",
		team: "Eddie Lake",
	},
	{
		id: 3,
		number: '2025-0003',
		header: "Executive summary",
		type: "Narrative",
		status: "For Billing",
		target: "10",
		serviceDate: "13",
		team: "Eddie Lake",
	},
	{
		id: 4,
		number: '2025-0004',
		header: "Technical approach",
		type: "Narrative",
		status: "Done",
		target: "27",
		serviceDate: "23",
		team: "Jamik Tashpulatov",
	},
	{
		id: 5,
		number: '2025-0005',
		header: "Design",
		type: "Narrative",
		status: "In Process",
		target: "2",
		serviceDate: "16",
		team: "Jamik Tashpulatov",
	},
	{
		id: 6,
		number: '2025-0006',
		header: "Capabilities",
		type: "Narrative",
		status: "In Process",
		target: "20",
		serviceDate: "8",
		team: "Jamik Tashpulatov",
	},
	{
		id: 7,
		header: "Integration with existing systems",
		type: "Narrative",
		status: "In Process",
		target: "19",
		serviceDate: "21",
		team: "Jamik Tashpulatov",
	},
	{
		id: 8,
		header: "Innovation and Advantages",
		type: "Narrative",
		status: "Done",
		target: "25",
		serviceDate: "26",
		team: "Assign team",
	},
	{
		id: 9,
		header: "Overview of EMR's Innovative Solutions",
		type: "Technical content",
		status: "Done",
		target: "7",
		serviceDate: "23",
		team: "Assign team",
	},
	{
		id: 10,
		header: "Advanced Algorithms and Machine Learning",
		type: "Narrative",
		status: "Done",
		target: "30",
		serviceDate: "28",
		team: "Assign team",
	},
	{
		id: 11,
		header: "Adaptive Communication Protocols",
		type: "Narrative",
		status: "Done",
		target: "9",
		serviceDate: "31",
		team: "Assign team",
	},
	{
		id: 12,
		header: "Advantages Over Current Technologies",
		type: "Narrative",
		status: "Done",
		target: "12",
		serviceDate: "0",
		team: "Assign team",
	},
	{
		id: 13,
		header: "Past Performance",
		type: "Narrative",
		status: "Done",
		target: "22",
		serviceDate: "33",
		team: "Assign team",
	},
	{
		id: 14,
		header: "Customer Feedback and Satisfaction Levels",
		type: "Narrative",
		status: "Done",
		target: "15",
		serviceDate: "34",
		team: "Assign team",
	},
	{
		id: 15,
		header: "Implementation Challenges and Solutions",
		type: "Narrative",
		status: "Done",
		target: "3",
		serviceDate: "35",
		team: "Assign team",
	},
	{
		id: 16,
		header: "Security Measures and Data Protection Policies",
		type: "Narrative",
		status: "In Process",
		target: "6",
		serviceDate: "36",
		team: "Assign team",
	},
	{
		id: 17,
		header: "Scalability and Future Proofing",
		type: "Narrative",
		status: "Done",
		target: "4",
		serviceDate: "37",
		team: "Assign team",
	},
	{
		id: 18,
		header: "Cost-Benefit Analysis",
		type: "Plain language",
		status: "Done",
		target: "14",
		serviceDate: "38",
		team: "Assign team",
	},
	{
		id: 19,
		header: "User Training and Onboarding Experience",
		type: "Narrative",
		status: "Done",
		target: "17",
		serviceDate: "39",
		team: "Assign team",
	},
	{
		id: 20,
		header: "Future Development Roadmap",
		type: "Narrative",
		status: "Done",
		target: "11",
		serviceDate: "40",
		team: "Assign team",
	},
	{
		id: 21,
		header: "System Architecture Overview",
		type: "Technical content",
		status: "In Process",
		target: "24",
		serviceDate: "18",
		team: "Maya Johnson",
	},
	{
		id: 22,
		header: "Risk Management Plan",
		type: "Narrative",
		status: "Done",
		target: "15",
		serviceDate: "22",
		team: "Carlos Rodriguez",
	},
	{
		id: 23,
		header: "Compliance Documentation",
		type: "Legal",
		status: "In Process",
		target: "31",
		serviceDate: "27",
		team: "Sarah Chen",
	},
	{
		id: 24,
		header: "API Documentation",
		type: "Technical content",
		status: "Done",
		target: "8",
		serviceDate: "12",
		team: "Raj Patel",
	},
	{
		id: 25,
		header: "User Interface Mockups",
		type: "Visual",
		status: "In Process",
		target: "19",
		serviceDate: "25",
		team: "Leila Ahmadi",
	},
	{
		id: 26,
		header: "Database Schema",
		type: "Technical content",
		status: "Done",
		target: "22",
		serviceDate: "20",
		team: "Thomas Wilson",
	},
	{
		id: 27,
		header: "Testing Methodology",
		type: "Technical content",
		status: "In Process",
		target: "17",
		serviceDate: "14",
		team: "Assign team",
	},
	{
		id: 28,
		header: "Deployment Strategy",
		type: "Narrative",
		status: "Done",
		target: "26",
		serviceDate: "30",
		team: "Eddie Lake",
	},
	{
		id: 29,
		header: "Budget Breakdown",
		type: "Financial",
		status: "In Process",
		target: "13",
		serviceDate: "16",
		team: "Jamik Tashpulatov",
	},
	{
		id: 30,
		header: "Market Analysis",
		type: "Research",
		status: "Done",
		target: "29",
		serviceDate: "32",
		team: "Sophia Martinez",
	},
	{
		id: 31,
		header: "Competitor Comparison",
		type: "Research",
		status: "In Process",
		target: "21",
		serviceDate: "19",
		team: "Assign team",
	},
	{
		id: 32,
		header: "Maintenance Plan",
		type: "Technical content",
		status: "Done",
		target: "16",
		serviceDate: "23",
		team: "Alex Thompson",
	},
	{
		id: 33,
		header: "User Personas",
		type: "Research",
		status: "In Process",
		target: "27",
		serviceDate: "24",
		team: "Nina Patel",
	},
	{
		id: 34,
		header: "Accessibility Compliance",
		type: "Legal",
		status: "Done",
		target: "18",
		serviceDate: "21",
		team: "Assign team",
	},
	{
		id: 35,
		header: "Performance Metrics",
		type: "Technical content",
		status: "In Process",
		target: "23",
		serviceDate: "26",
		team: "David Kim",
	},
	{
		id: 36,
		header: "Disaster Recovery Plan",
		type: "Technical content",
		status: "Done",
		target: "14",
		serviceDate: "17",
		team: "Jamik Tashpulatov",
	},
	{
		id: 37,
		header: "Third-party Integrations",
		type: "Technical content",
		status: "In Process",
		target: "25",
		serviceDate: "28",
		team: "Eddie Lake",
	},
	{
		id: 38,
		header: "User Feedback Summary",
		type: "Research",
		status: "Done",
		target: "20",
		serviceDate: "15",
		team: "Assign team",
	},
	{
		id: 39,
		header: "Localization Strategy",
		type: "Narrative",
		status: "In Process",
		target: "12",
		serviceDate: "19",
		team: "Maria Garcia",
	},
	{
		id: 40,
		header: "Mobile Compatibility",
		type: "Technical content",
		status: "Done",
		target: "28",
		serviceDate: "31",
		team: "James Wilson",
	},
	{
		id: 41,
		header: "Data Migration Plan",
		type: "Technical content",
		status: "In Process",
		target: "19",
		serviceDate: "22",
		team: "Assign team",
	},
	{
		id: 42,
		header: "Quality Assurance Protocols",
		type: "Technical content",
		status: "Done",
		target: "30",
		serviceDate: "33",
		team: "Priya Singh",
	},
	{
		id: 43,
		header: "Stakeholder Analysis",
		type: "Research",
		status: "In Process",
		target: "11",
		serviceDate: "14",
		team: "Eddie Lake",
	},
	{
		id: 44,
		header: "Environmental Impact Assessment",
		type: "Research",
		status: "Done",
		target: "24",
		serviceDate: "27",
		team: "Assign team",
	},
	{
		id: 45,
		header: "Intellectual Property Rights",
		type: "Legal",
		status: "In Process",
		target: "17",
		serviceDate: "20",
		team: "Sarah Johnson",
	},
	{
		id: 46,
		header: "Customer Support Framework",
		type: "Narrative",
		status: "Done",
		target: "22",
		serviceDate: "25",
		team: "Jamik Tashpulatov",
	},
	{
		id: 47,
		header: "Version Control Strategy",
		type: "Technical content",
		status: "In Process",
		target: "15",
		serviceDate: "18",
		team: "Assign team",
	},
	{
		id: 48,
		header: "Continuous Integration Pipeline",
		type: "Technical content",
		status: "Done",
		target: "26",
		serviceDate: "29",
		team: "Michael Chen",
	},
	{
		id: 49,
		header: "Regulatory Compliance",
		type: "Legal",
		status: "In Process",
		target: "13",
		serviceDate: "16",
		team: "Assign team",
	},
	{
		id: 50,
		header: "User Authentication System",
		type: "Technical content",
		status: "Done",
		target: "28",
		serviceDate: "31",
		team: "Eddie Lake",
	},
	{
		id: 51,
		header: "Data Analytics Framework",
		type: "Technical content",
		status: "In Process",
		target: "21",
		serviceDate: "24",
		team: "Jamik Tashpulatov",
	},
	{
		id: 52,
		header: "Cloud Infrastructure",
		type: "Technical content",
		status: "Done",
		target: "16",
		serviceDate: "19",
		team: "Assign team",
	},
	{
		id: 53,
		header: "Network Security Measures",
		type: "Technical content",
		status: "In Process",
		target: "29",
		serviceDate: "32",
		team: "Lisa Wong",
	},
	{
		id: 54,
		header: "Project Timeline",
		type: "Planning",
		status: "Done",
		target: "14",
		serviceDate: "17",
		team: "Eddie Lake",
	},
	{
		id: 55,
		header: "Resource Allocation",
		type: "Planning",
		status: "In Process",
		target: "27",
		serviceDate: "30",
		team: "Assign team",
	},
	{
		id: 56,
		header: "Team Structure and Roles",
		type: "Planning",
		status: "Done",
		target: "20",
		serviceDate: "23",
		team: "Jamik Tashpulatov",
	},
	{
		id: 57,
		header: "Communication Protocols",
		type: "Planning",
		status: "In Process",
		target: "15",
		serviceDate: "18",
		team: "Assign team",
	},
	{
		id: 58,
		header: "Success Metrics",
		type: "Planning",
		status: "Done",
		target: "30",
		serviceDate: "33",
		team: "Eddie Lake",
	},
	{
		id: 59,
		header: "Internationalization Support",
		type: "Technical content",
		status: "In Process",
		target: "23",
		serviceDate: "26",
		team: "Jamik Tashpulatov",
	},
	{
		id: 60,
		header: "Backup and Recovery Procedures",
		type: "Technical content",
		status: "Done",
		target: "18",
		serviceDate: "21",
		team: "Assign team",
	},
	{
		id: 61,
		header: "Monitoring and Alerting System",
		type: "Technical content",
		status: "In Process",
		target: "25",
		serviceDate: "28",
		team: "Daniel Park",
	},
	{
		id: 62,
		header: "Code Review Guidelines",
		type: "Technical content",
		status: "Done",
		target: "12",
		serviceDate: "15",
		team: "Eddie Lake",
	},
	{
		id: 63,
		header: "Documentation Standards",
		type: "Technical content",
		status: "In Process",
		target: "27",
		serviceDate: "30",
		team: "Jamik Tashpulatov",
	},
	{
		id: 64,
		header: "Release Management Process",
		type: "Planning",
		status: "Done",
		target: "22",
		serviceDate: "25",
		team: "Assign team",
	},
	{
		id: 65,
		header: "Feature Prioritization Matrix",
		type: "Planning",
		status: "In Process",
		target: "19",
		serviceDate: "22",
		team: "Emma Davis",
	},
	{
		id: 66,
		header: "Technical Debt Assessment",
		type: "Technical content",
		status: "Done",
		target: "24",
		serviceDate: "27",
		team: "Eddie Lake",
	},
	{
		id: 67,
		header: "Capacity Planning",
		type: "Planning",
		status: "In Process",
		target: "21",
		serviceDate: "24",
		team: "Jamik Tashpulatov",
	},
	{
		id: 68,
		header: "Service Level Agreements",
		type: "Legal",
		status: "Done",
		target: "26",
		serviceDate: "29",
		team: "Assign team",
	},
];